'use client';
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';
import { configureBoneyard } from 'boneyard-js/react';

import _page_forgot_password from './page-forgot-password.bones.json';
import _page_home from './page-home.bones.json';
import _page_login from './page-login.bones.json';

configureBoneyard({
    color: 'var(--muted)',
    darkColor: 'var(--muted)',
    animate: 'pulse',
    transition: 160,
});

registerBones({
    'page-home': _page_home,
    'page-login': _page_login,
    'page-forgot-password': _page_forgot_password,
});
